apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabapp-deploy
  namespace: redamix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabapp-server
  template:
    metadata:
      labels:
        app: diabapp-server
    spec:
      containers:
        - name: diabapp-server
          image: 10.0.2.10:32000/diabapp-server:v1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
