apiVersion: v1
kind: Service
metadata:
  name: diabapp-svc
  namespace: redamix
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31111
      protocol: TCP
  selector:
    app: diabapp-server
